### ISSUE TITLE
Add an estimate of the ISO final filesize in the project documentation

### ISSUE THREAD

**Issue by Jonas-fr** [shadlyd15/DoomLinux#1]
Everything is in the title! The script's explanation is top notch and few metrics added on top of that couldn't hurt!

**Comment by tslug** [comment]
> Everything is in the title! The script's explanation is top notch and few metrics added on top of that couldn't hurt!

Beat me to it.  That's literally what I came here to ask.  :)

**Comment by shadlyd15** [comment]
Estimated size of compiled binaries added.

**Comment by Jonas-fr** [comment]
Thanks!
