### ISSUE TITLE
Unnecessary SDL Dependencies

### ISSUE THREAD

**Issue by rnsi** [shadlyd15/DoomLinux#3]
On a fresh install of Debian 10, without desktop, I had to install unzip, rsync, libsdl1* and libsdl2*.

The last two can probably be reduced, but I didn't test.

**Comment by shadlyd15** [comment]
@rnsi unzip rsync mtools added as build dependency. libsdl dependency removed from fbDoom.

**Comment by rnsi** [comment]
Still need libsdl:

[Linking fbdoom]
/usr/bin/ld: cannot find -lSDL
collect2: error: ld returned 1 exit status
make: *** [Makefile:49: fbdoom] Error 1

Also, there's a prompt that pauses the config:

*
* Build Options
*
Build static binary (no shared libs) (STATIC) [Y/n/?] y
Force NOMMU build (NOMMU) [N/y/?] n
Cross compiler prefix (CROSS_COMPILER_PREFIX) []
Path to sysroot (SYSROOT) []
Additional CFLAGS (EXTRA_CFLAGS) []
Additional LDFLAGS (EXTRA_LDFLAGS) []
Additional LDLIBS (EXTRA_LDLIBS) []
Avoid using GCC-specific code constructs (USE_PORTABLE_CODE) [N/y/?] n
Use -mpreferred-stack-boundary=2 on i386 arch (STACK_OPTIMIZATION_386) [Y/n/?] y
Use -static-libgcc (STATIC_LIBGCC) [Y/n/?] (NEW)

**Comment by shadlyd15** [comment]
@rnsi Both the issues should be gone now.

**Comment by rnsi** [comment]
I can confirm both issues appear to be resolved.

Good job.
