### ISSUE TITLE
when i put ./DoomLinux.sh it says Permission denied

### ISSUE THREAD

**Issue by Wishfulzebra242** [shadlyd15/DoomLinux#8]

**Comment by shadlyd15** [comment]
Please try with sudo ./DoomLinux.sh

**Comment by Wishfulzebra242** [comment]
I did it and it said command not found
I'm on Chromebook linux  fyi

**Comment by Wishfulzebra242** [comment]
Here is an image of it
![Screenshot 2023-03-15 15 08 38](https://user-images.githubusercontent.com/126366734/225455394-6faf986d-72e1-4925-9f78-16dc541051e2.png)

**Comment by shadlyd15** [comment]
Please try 
chmod 777 DoomLinux.sh
 sudo ./DoomLinux.sh

**Comment by shadlyd15** [comment]
Assuming the issue is solved.
