### ISSUE TITLE
Seems to want SDL...

### ISSUE THREAD

**Issue by gary9872** [shadlyd15/DoomLinux#9]
Script fails because SDL is not found.

I assume changes where made in fbDOOM code since your last commit? Or do I need to install sdl? But that starts breaking everything if I would need to do so.

cheers,

gary

**Comment by shadlyd15** [comment]
Hello @gary9872 . I removed the the part where you need SDL. So ideally it should not ask for SDL in the latest script. Can you please share the output what you are getting? It will help me to figure out what is going wrong.

**Comment by gary9872** [comment]
I assumed I should be using the 1.0 release script. I assume you are talking about the latest commit. To that end I have tried the latest commit instead.

The SDL issue is gone. I can see sed applied changes properly to the fbDoom Makefile.

However now there are other issues arising, but this issue is solved.
